import { Platform } from "react-native";

const primaryOrange = "#FF8C00";
const primaryLight = "#FFB347";
const primaryDark = "#E67E00";
const secondaryOrange = "#FFF3E0";
const accentOrange = "#FF6B35";

export const Colors = {
  light: {
    primary: primaryOrange,
    primaryLight: primaryLight,
    primaryDark: primaryDark,
    secondary: secondaryOrange,
    accent: accentOrange,
    text: "#1A1A1A",
    textSecondary: "#666666",
    textTertiary: "#999999",
    textMuted: "#CCCCCC",
    textGray: "#7F8C8D",
    buttonText: "#FFFFFF",
    tabIconDefault: "#999999",
    tabIconSelected: primaryOrange,
    link: primaryOrange,
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#F5F5F5",
    backgroundSecondary: "#FAFAFA",
    backgroundTertiary: "#EEEEEE",
    backgroundCard: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    border: "#E5E5E5",
    borderLight: "#F0F0F0",
    borderDark: "#CCCCCC",
    divider: "#EEEEEE",
    success: "#00C853",
    successLight: "#E8F5E9",
    warning: "#FFB300",
    warningLight: "#FFF8E1",
    error: "#FF3D00",
    errorLight: "#FFEBEE",
    info: "#2196F3",
    infoLight: "#E3F2FD",
    discount: "#E53935",
    discountBg: "#FFEBEE",
    rating: "#FFB400",
    skeleton: "#E5E5E5",
    skeletonHighlight: "#F5F5F5",
    overlay: "rgba(0,0,0,0.5)",
    overlayLight: "rgba(0,0,0,0.3)",
    boyFashion: "#2196F3",
    girlFashion: "#FF8C00",
    footwear: "#F39C12",
    toys: "#9B59B6",
    diapers: "#27AE60",
    winter: "#5C6BC0",
    summer: "#FF7043",
    festive: "#AB47BC",
    monsoon: "#26A69A",
  },
  dark: {
    primary: primaryOrange,
    primaryLight: primaryLight,
    primaryDark: primaryDark,
    secondary: "#3D2E1F",
    accent: accentOrange,
    text: "#FFFFFF",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    textMuted: "#4D4D4D",
    textGray: "#9BA1A6",
    buttonText: "#FFFFFF",
    tabIconDefault: "#808080",
    tabIconSelected: primaryOrange,
    link: primaryOrange,
    backgroundRoot: "#121212",
    backgroundDefault: "#1A1A1A",
    backgroundSecondary: "#242424",
    backgroundTertiary: "#2E2E2E",
    backgroundCard: "#1E1E1E",
    surface: "#1E1E1E",
    surfaceElevated: "#2A2A2A",
    border: "#333333",
    borderLight: "#2A2A2A",
    borderDark: "#444444",
    divider: "#333333",
    success: "#00E676",
    successLight: "#1B3D2F",
    warning: "#FFCA28",
    warningLight: "#3D3520",
    error: "#FF5252",
    errorLight: "#3D1F1F",
    info: "#448AFF",
    infoLight: "#1F2D3D",
    discount: "#FF5252",
    discountBg: "#3D1F1F",
    rating: "#FFD54F",
    skeleton: "#333333",
    skeletonHighlight: "#444444",
    overlay: "rgba(0,0,0,0.7)",
    overlayLight: "rgba(0,0,0,0.5)",
    boyFashion: "#2196F3",
    girlFashion: "#FF8C00",
    footwear: "#F39C12",
    toys: "#9B59B6",
    diapers: "#27AE60",
    winter: "#7986CB",
    summer: "#FF8A65",
    festive: "#BA68C8",
    monsoon: "#4DB6AC",
  },
};

export const Gradients = {
  primary: [primaryOrange, primaryLight],
  primaryReverse: [primaryLight, primaryOrange],
  warm: ["#FF8C00", "#FF6B35"],
  sunset: ["#FF8C00", "#FF4500"],
  soft: ["#FFF3E0", "#FFFFFF"],
  card: ["#FFFFFF", "#FAFAFA"],
  overlay: ["rgba(0,0,0,0)", "rgba(0,0,0,0.6)"],
  success: ["#00C853", "#00E676"],
  winter: ["#5C6BC0", "#7986CB"],
  summer: ["#FF7043", "#FFAB91"],
  festive: ["#AB47BC", "#CE93D8"],
  monsoon: ["#26A69A", "#80CBC4"],
};

export const Spacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  xxxxl: 40,
  huge: 48,
  massive: 64,
  inputHeight: 48,
  buttonHeight: 52,
  buttonHeightSmall: 40,
  buttonHeightLarge: 56,
  headerHeight: 56,
  tabBarHeight: 60,
  bottomSheetHandle: 24,
  cardPadding: 16,
  screenPadding: 16,
  sectionSpacing: 24,
  listItemSpacing: 12,
  gridGap: 12,
};

export const BorderRadius = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  "2xl": 40,
  "3xl": 50,
  full: 9999,
  card: 0,
  productCard: 0,
  button: 12,
  buttonSmall: 8,
  buttonPill: 9999,
  input: 12,
  modal: 24,
  bottomSheet: 24,
  chip: 20,
  badge: 6,
  avatar: 9999,
};

export const Typography = {
  displayLarge: {
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 40,
    letterSpacing: -0.5,
  },
  displayMedium: {
    fontSize: 28,
    fontWeight: "700" as const,
    lineHeight: 36,
    letterSpacing: -0.25,
  },
  h1: {
    fontSize: 24,
    fontWeight: "700" as const,
    lineHeight: 32,
  },
  h2: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
  },
  h3: {
    fontSize: 18,
    fontWeight: "600" as const,
    lineHeight: 26,
  },
  h4: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 24,
  },
  bodyLarge: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 24,
  },
  body: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 22,
  },
  bodySmall: {
    fontSize: 13,
    fontWeight: "400" as const,
    lineHeight: 20,
  },
  small: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 18,
  },
  caption: {
    fontSize: 11,
    fontWeight: "400" as const,
    lineHeight: 16,
  },
  overline: {
    fontSize: 10,
    fontWeight: "600" as const,
    lineHeight: 14,
    letterSpacing: 1,
    textTransform: "uppercase" as const,
  },
  button: {
    fontSize: 15,
    fontWeight: "600" as const,
    lineHeight: 22,
  },
  buttonSmall: {
    fontSize: 13,
    fontWeight: "600" as const,
    lineHeight: 18,
  },
  link: {
    fontSize: 14,
    fontWeight: "500" as const,
    lineHeight: 22,
  },
  price: {
    fontSize: 18,
    fontWeight: "700" as const,
    lineHeight: 24,
  },
  priceSmall: {
    fontSize: 14,
    fontWeight: "700" as const,
    lineHeight: 20,
  },
  priceLarge: {
    fontSize: 24,
    fontWeight: "700" as const,
    lineHeight: 32,
  },
  strikethrough: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 18,
    textDecorationLine: "line-through" as const,
  },
  discount: {
    fontSize: 12,
    fontWeight: "700" as const,
    lineHeight: 16,
  },
};

export const Shadows = {
  none: {
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  xs: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  sm: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  lg: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  xl: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  xxl: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 12,
  },
  floating: {
    shadowColor: primaryOrange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  bottomSheet: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 16,
  },
  stickyFooter: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
  },
  small: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  medium: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  large: {
    shadowColor: primaryOrange,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
};

export const Elevation = {
  level0: 0,
  level1: 1,
  level2: 2,
  level3: 4,
  level4: 6,
  level5: 8,
  card: 2,
  appBar: 4,
  fab: 6,
  drawer: 16,
  modal: 24,
  bottomSheet: 16,
  snackbar: 6,
  tooltip: 8,
};

export const ZIndex = {
  base: 0,
  content: 1,
  header: 100,
  sticky: 200,
  dropdown: 300,
  overlay: 400,
  modal: 500,
  toast: 600,
  tooltip: 700,
  max: 9999,
};

export const Animation = {
  duration: {
    instant: 0,
    fastest: 100,
    fast: 200,
    normal: 300,
    slow: 400,
    slower: 500,
    slowest: 700,
  },
  easing: {
    linear: "linear",
    easeIn: "ease-in",
    easeOut: "ease-out",
    easeInOut: "ease-in-out",
  },
};

export const IconSize = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 28,
  xxl: 32,
  xxxl: 40,
  huge: 48,
  massive: 64,
  tabBar: 24,
  header: 24,
  button: 20,
  badge: 12,
  rating: 14,
};

export const ButtonVariants = {
  primary: {
    backgroundColor: primaryOrange,
    textColor: "#FFFFFF",
    borderColor: "transparent",
    borderWidth: 0,
  },
  secondary: {
    backgroundColor: secondaryOrange,
    textColor: primaryOrange,
    borderColor: "transparent",
    borderWidth: 0,
  },
  outline: {
    backgroundColor: "transparent",
    textColor: primaryOrange,
    borderColor: primaryOrange,
    borderWidth: 1.5,
  },
  ghost: {
    backgroundColor: "transparent",
    textColor: primaryOrange,
    borderColor: "transparent",
    borderWidth: 0,
  },
  danger: {
    backgroundColor: "#FF3D00",
    textColor: "#FFFFFF",
    borderColor: "transparent",
    borderWidth: 0,
  },
  success: {
    backgroundColor: "#00C853",
    textColor: "#FFFFFF",
    borderColor: "transparent",
    borderWidth: 0,
  },
  disabled: {
    backgroundColor: "#E5E5E5",
    textColor: "#999999",
    borderColor: "transparent",
    borderWidth: 0,
  },
};

export const InputVariants = {
  default: {
    backgroundColor: "#F5F5F5",
    borderColor: "#E5E5E5",
    borderWidth: 1,
    focusBorderColor: primaryOrange,
  },
  outlined: {
    backgroundColor: "transparent",
    borderColor: "#E5E5E5",
    borderWidth: 1.5,
    focusBorderColor: primaryOrange,
  },
  filled: {
    backgroundColor: "#F5F5F5",
    borderColor: "transparent",
    borderWidth: 0,
    focusBorderColor: primaryOrange,
  },
};

export const ProductCardDimensions = {
  aspectRatio: 1,
  imageAspectRatio: 1.2,
  minWidth: 150,
  maxWidth: 200,
  gridColumns: 2,
  gridGap: 1,
  borderRadius: 0,
  padding: 0,
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const ScreenBreakpoints = {
  small: 360,
  medium: 480,
  large: 768,
  xlarge: 1024,
};

export const HitSlop = {
  small: { top: 8, bottom: 8, left: 8, right: 8 },
  medium: { top: 12, bottom: 12, left: 12, right: 12 },
  large: { top: 16, bottom: 16, left: 16, right: 16 },
};
